// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-AddOutline',
  name: 'AddOutline',
  content: '<svg viewBox="0 0 48 48"><path d="M25.1 6.5c.22 0 .4.18.4.4v15.6h15.6c.22 0 .4.18.4.4v2.2a.4.4 0 01-.4.4H25.5v15.6a.4.4 0 01-.4.4h-2.2a.4.4 0 01-.4-.4V25.5H6.9a.4.4 0 01-.4-.4v-2.2c0-.22.18-.4.4-.4h15.6V6.9c0-.22.18-.4.4-.4h2.2z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
