// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-AddSquareOutline',
  name: 'AddSquareOutline',
  content: '<svg viewBox="0 0 49 48"><path d="M39 4a6 6 0 016 6v28a6 6 0 01-6 6H11a6 6 0 01-6-6V10a6 6 0 016-6h28zm0 3H11a3 3 0 00-2.995 2.824L8 10v28a3 3 0 002.824 2.995L11 41h28a3 3 0 002.995-2.824L42 38V10a3 3 0 00-2.824-2.995L39 7zm-12.9 7.4l-.001 7.6H33.7c.22 0 .4.18.4.4v2.2a.4.4 0 01-.4.4h-7.601v7.6a.4.4 0 01-.399.4h-2.2a.4.4 0 01-.4-.4l-.001-7.6H15.5a.4.4 0 01-.4-.4v-2.2c0-.22.18-.4.4-.4h7.599v-7.6c.001-.22.18-.4.401-.4h2.2a.4.4 0 01.4.4z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
