// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-ArrowDownCircleOutline',
  name: 'ArrowDownCircleOutline',
  content: '<svg viewBox="0 0 48 48"><path d="M24 2c12.15 0 22 9.85 22 22s-9.85 22-22 22S2 36.15 2 24 11.85 2 24 2zm0 3C13.507 5 5 13.507 5 24s8.507 19 19 19 19-8.507 19-19S34.493 5 24 5zm1.5 9v14.097l6.5-5.86v4.033l-6.942 6.261-.132.106a1.494 1.494 0 01-.752.275l-.174.004a1.496 1.496 0 01-.942-.29l-.116-.095L16 26.271v-4.035l6.5 5.863V14h3z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
