// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-CheckShieldFill',
  name: 'CheckShieldFill',
  content: '<svg viewBox="0 0 48 48"><path d="M23.583 4.017L39.86 7.349C41.694 7.75 43 9.357 43 11.214v18.553a7.902 7.902 0 01-4.121 6.922l-13.44 6.823a4.037 4.037 0 01-3.878 0L9.12 36.69A7.902 7.902 0 015 29.767V11.214C5 9.357 6.306 7.75 8.14 7.35l15.277-3.331a.4.4 0 01.166-.001zm9.123 14.986H29.6a.4.4 0 00-.28.116l-6.481 6.41-3.48-3.441a.4.4 0 00-.28-.116h-3.105a.4.4 0 00-.281.684l5.74 5.68c.369.365.845.558 1.326.577h.16l.16-.013c.426-.051.839-.24 1.167-.564l8.741-8.648a.4.4 0 00-.281-.685z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
