// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-CheckCircleFill',
  name: 'CheckCircleFill',
  content: '<svg viewBox="0 0 48 48"><path d="M24 2c12.15 0 22 9.85 22 22s-9.85 22-22 22S2 36.15 2 24 11.85 2 24 2zm11.82 15H32.71a.4.4 0 00-.283.117L21.392 28.15l-5.033-5.033a.4.4 0 00-.283-.117h-3.11a.4.4 0 00-.284.683 2625496.36 2625496.36 0 00.674.674l.31.31 2.186 2.2.585.591c1.818 1.835 3.561 3.6 3.83 3.872l.034.034a1.5 1.5 0 002.121 0l13.681-13.68A.4.4 0 0035.82 17z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
