// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-CloseCircleFill',
  name: 'CloseCircleFill',
  content: '<svg viewBox="0 0 48 48"><path d="M24 2c12.15 0 22 9.85 22 22s-9.85 22-22 22S2 36.15 2 24 11.85 2 24 2zm-5.325 14h-3.111a.4.4 0 00-.283.683l7.018 7.018-7.616 7.616a.4.4 0 00.283.683h3.11a.4.4 0 00.282-.117l6.062-6.061 6.062 6.06a.4.4 0 00.283.118h3.111a.4.4 0 00.283-.683L26.542 23.7l7.017-7.017a.4.4 0 00-.283-.683h-3.112a.4.4 0 00-.283.117l-5.46 5.462-5.463-5.462a.4.4 0 00-.283-.117z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
