// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-CompassOutline',
  name: 'CompassOutline',
  content: '<svg viewBox="0 0 48 48"><path d="M24 2c12.15 0 22 9.85 22 22s-9.85 22-22 22S2 36.15 2 24 11.85 2 24 2zm0 3C13.507 5 5 13.507 5 24s8.507 19 19 19 19-8.507 19-19S34.493 5 24 5zm9.38 10.716c.147.405.147.849 0 1.253l-4.258 9.96a3.667 3.667 0 01-2.193 2.193l-9.96 4.258a1.833 1.833 0 01-2.35-2.35l4.259-9.959a3.667 3.667 0 012.193-2.193l9.96-4.258a1.833 1.833 0 012.35 1.096zm-3.256 2.16l-8.113 3.587a.917.917 0 00-.503.442l-.045.106-3.587 8.113 8.113-3.587a.917.917 0 00.503-.441l.045-.107 3.587-8.113z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
