// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-DeleteOutline',
  name: 'DeleteOutline',
  content: '<svg viewBox="0 0 48 48"><path d="M33 3a3 3 0 013 3v3h6.6c.22 0 .4.18.4.4v2.2a.4.4 0 01-.4.4H41v27a6 6 0 01-6 6H13a6 6 0 01-6-6V12H5.4a.4.4 0 01-.4-.4V9.4c0-.22.18-.4.4-.4H12V6a3 3 0 013-3h18zm5 9H10v27a3 3 0 002.824 2.995L13 42h22a3 3 0 002.995-2.824L38 39V12zm-18.4 6c.22 0 .4.18.4.4v17.2a.4.4 0 01-.4.4h-2.2a.4.4 0 01-.4-.4V18.4c0-.22.18-.4.4-.4h2.2zm12 0c.22 0 .4.18.4.4v17.2a.4.4 0 01-.4.4h-2.2a.4.4 0 01-.4-.4V18.4c0-.22.18-.4.4-.4h2.2zM33 6H15v3h18V6z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
