// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-DownOutline',
  name: 'DownOutline',
  content: '<svg viewBox="0 0 48 48"><path d="M5.112 16.395l17.55 18.182a1.495 1.495 0 002.014.097l.107-.097 18.1-18.181a.4.4 0 00.117-.283v-3.126a.4.4 0 00-.683-.283L23.782 31.32 5.687 12.724a.4.4 0 00-.687.279v3.114a.4.4 0 00.112.278z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
