// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-DownlandOutline',
  name: 'DownlandOutline',
  content: '<svg viewBox="0 0 48 48"><path d="M13.5 4.4v2.2a.4.4 0 01-.4.4H10a3 3 0 00-2.995 2.824L7 10v28a3 3 0 002.824 2.995L10 41h28a3 3 0 002.995-2.824L41 38V10a3 3 0 00-2.824-2.995L38 7h-2.1a.4.4 0 01-.4-.4V4.4c0-.22.18-.4.4-.4H38a6 6 0 016 6v28a6 6 0 01-6 6H10a6 6 0 01-6-6V10a6 6 0 016-6h3.1c.22 0 .4.18.4.4zm12.5 0v21.64l7.955-7.269a.022.022 0 01.03.001.05.05 0 01.015.036v3.805a.4.4 0 01-.13.295l-8.277 7.565a1.565 1.565 0 01-1.107.41 1.565 1.565 0 01-1.108-.41l-8.248-7.537a.4.4 0 01-.13-.295v-2.976a.4.4 0 01.67-.295L23 26.068V4.4c0-.22.18-.4.4-.4h2.2c.22 0 .4.18.4.4z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
