// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-DownFill',
  name: 'DownFill',
  content: '<svg viewBox="0 0 48 48"><path d="M40.664 13H7.341c-.765 0-1.508.262-2.102.735a3.29 3.29 0 00-.496 4.655l16.661 20.383a3.367 3.367 0 005.197 0L43.258 18.39A3.278 3.278 0 0044 16.308C44.005 14.48 42.506 13 40.664 13z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
