// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-EditFill',
  name: 'EditFill',
  content: '<svg viewBox="0 0 48 48"><path d="M27.533 13.846l7.423 7.22c.41.398.41 1.044 0 1.443L15.217 41.702a1.066 1.066 0 01-.742.298H8.1C6.94 42 6 41.086 6 39.958v-6.197c0-.27.11-.53.307-.723l19.74-19.192a1.071 1.071 0 011.486 0zm12.621-5.053a6.006 6.006 0 01.001 8.663L38.67 18.9a1.071 1.071 0 01-1.486 0l-7.424-7.22a1.001 1.001 0 010-1.444l1.485-1.442c2.46-2.392 6.449-2.392 8.91 0v-.001z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
