// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-ExclamationShieldFill',
  name: 'ExclamationShieldFill',
  content: '<svg viewBox="0 0 48 48"><path d="M23.583 4.017L39.86 7.349C41.694 7.75 43 9.357 43 11.214v18.553a7.902 7.902 0 01-4.121 6.922l-13.44 6.823a4.037 4.037 0 01-3.878 0L9.12 36.69A7.902 7.902 0 015 29.767V11.214C5 9.357 6.306 7.75 8.14 7.35l15.277-3.331a.4.4 0 01.166-.001zM25.1 30.006h-2.2a.4.4 0 00-.4.4v2.2c0 .221.18.4.4.4h2.2a.4.4 0 00.4-.4v-2.2a.4.4 0 00-.4-.4zm0-16.004h-2.2a.4.4 0 00-.4.4v12.203c0 .221.18.4.4.4h2.2a.4.4 0 00.4-.4V14.402a.4.4 0 00-.4-.4z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
