// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-FireFill',
  name: 'FireFill',
  content: '<svg viewBox="0 0 48 48"><path d="M28.81 7.566c1.808 3.659.934 6.89.559 8.981s-1.537 5.12-2.557 6.434c-1.359 1.749-1.715 3.865.375 4.934 3.612 1.104 7.95-7.175 5.81-15.436v-.104C38.295 17.78 40.964 23.731 41 30.23c0 .302-.07.597-.094.9C40.06 41.512 31.176 46 24.97 46c-6.207 0-19.851-2.316-17.753-19.702.893-6.296 6.435-9.96 9.289-13.258 1.6-1.85 3.757-4.095 6.58-11.04 2.974 1.539 4.778 3.626 5.725 5.566z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
