// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-FrownOutline',
  name: 'FrownOutline',
  content: '<svg viewBox="0 0 48 48"><path d="M24 2c12.15 0 22 9.85 22 22s-9.85 22-22 22S2 36.15 2 24 11.85 2 24 2zm0 3C13.507 5 5 13.507 5 24s8.507 19 19 19 19-8.507 19-19S34.493 5 24 5zm0 21a19.91 19.91 0 019.798 2.56.4.4 0 01.203.348v2.584a.4.4 0 01-.625.33 13.137 13.137 0 00-.301-.2A16.92 16.92 0 0024 29c-3.34 0-6.454.963-9.082 2.627-.054.034-.152.1-.293.195a.4.4 0 01-.625-.33v-2.584a.4.4 0 01.206-.35A19.91 19.91 0 0124 26zm-8-8a2 2 0 110 4 2 2 0 010-4zm16 0a2 2 0 110 4 2 2 0 010-4z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
