// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-HistogramOutline',
  name: 'HistogramOutline',
  content: '<svg viewBox="0 0 48 48"><path d="M39.5 13a4 4 0 014 4v21a4 4 0 01-4 4h-3a4 4 0 01-4-4V17a4 4 0 014-4h3zm-14-7a4 4 0 014 4v28a4 4 0 01-4 4h-3a4 4 0 01-4-4V10a4 4 0 014-4h3zm-14 17a4 4 0 014 4v11a4 4 0 01-4 4h-3a4 4 0 01-4-4V27a4 4 0 014-4h3zm28-7h-3a1 1 0 00-.993.883L35.5 17v21a1 1 0 00.883.993L36.5 39h3a1 1 0 00.993-.883L40.5 38V17a1 1 0 00-.883-.993L39.5 16zm-14-7h-3a1 1 0 00-.993.883L21.5 10v28a1 1 0 00.883.993L22.5 39h3a1 1 0 00.993-.883L26.5 38V10a1 1 0 00-.883-.993L25.5 9zm-14 17h-3a1 1 0 00-.993.883L7.5 27v11a1 1 0 00.883.993L8.5 39h3a1 1 0 00.993-.883L12.5 38V27a1 1 0 00-.883-.993L11.5 26z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
