// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-InformationCircleOutline',
  name: 'InformationCircleOutline',
  content: '<svg viewBox="0 0 49 48"><path d="M25 2c12.15 0 22 9.85 22 22s-9.85 22-22 22S3 36.15 3 24 12.85 2 25 2zm0 3C14.507 5 6 13.507 6 24s8.507 19 19 19 19-8.507 19-19S35.493 5 25 5zm1.6 15c.22 0 .4.18.4.4v14.2a.4.4 0 01-.4.4h-2.2a.4.4 0 01-.4-.4V23h-1.6a.4.4 0 01-.4-.4v-2.2c0-.22.18-.4.4-.4h4.2zm0-6c.22 0 .4.18.4.4v2.2a.4.4 0 01-.4.4h-2.2a.4.4 0 01-.4-.4v-2.2c0-.22.18-.4.4-.4h2.2z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
