// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-InformationCircleFill',
  name: 'InformationCircleFill',
  content: '<svg viewBox="0 0 48 48"><path d="M24 2c12.15 0 22 9.85 22 22s-9.85 22-22 22S2 36.15 2 24 11.85 2 24 2zm1.6 18h-4.2a.4.4 0 00-.4.4v2.2c0 .22.18.4.4.4h1.2c.22 0 .4.18.4.4v11.2c0 .22.18.4.4.4h2.2a.4.4 0 00.4-.4V20.4a.4.4 0 00-.4-.4zm0-6h-2.2a.4.4 0 00-.4.4v2.2c0 .22.18.4.4.4h2.2a.4.4 0 00.4-.4v-2.2a.4.4 0 00-.4-.4z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
