// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-LockFill',
  name: 'LockFill',
  content: '<svg viewBox="0 0 48 48"><path d="M24 4c6.802 0 12.316 5.543 12.316 12.38v5.715c3.14 0 5.684 2.559 5.684 5.715v10.476C42 41.442 39.455 44 36.316 44H11.684C8.544 44 6 41.442 6 38.286V27.81c0-3.156 2.545-5.715 5.684-5.715v-5.714C11.684 9.543 17.198 4 24 4zm1.516 25.714h-2.084a.38.38 0 00-.38.381v4.953c0 .21.171.38.38.38h2.084a.38.38 0 00.379-.38v-4.953a.38.38 0 00-.38-.38zM24 6.857c-5.144 0-9.33 4.121-9.47 9.257l-.004.267v5.714h18.948v-5.714c0-5.171-4.1-9.38-9.209-9.52L24 6.857z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
