// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-MailOutline',
  name: 'MailOutline',
  content: '<svg viewBox="0 0 48 48"><path d="M39 6a6 6 0 016 6v24a6 6 0 01-6 6H9a6 6 0 01-6-6V12a6 6 0 016-6h30zm3 9.5l-17.83 8.42a.4.4 0 01-.34 0L6 15.5V36a3 3 0 002.824 2.995L9 39h30a3 3 0 002.995-2.824L42 36V15.5zM39 9H9a3 3 0 00-2.995 2.824L6 12v.146l17.83 8.418a.4.4 0 00.34 0L42 12.145V12a3 3 0 00-2.824-2.995L39 9z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
