// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-MessageFill',
  name: 'MessageFill',
  content: '<svg viewBox="0 0 48 48"><path d="M24 5c11.045 0 20 8.507 20 19 0 10.382-8.765 18.819-19.648 18.997L24 43a20.725 20.725 0 01-9.917-2.497l-4.96 2.148a1.822 1.822 0 01-2.393-.939 1.802 1.802 0 01-.1-1.14l1.267-5.301C5.447 32.117 4 28.219 4 24 4 13.507 12.955 5 24 5zm-7.75 17a1.75 1.75 0 000 3.5 1.75 1.75 0 000-3.5zm16 0a1.75 1.75 0 000 3.5 1.75 1.75 0 000-3.5zm-8 0a1.75 1.75 0 000 3.5 1.75 1.75 0 000-3.5z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
