// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-MinusOutline',
  name: 'MinusOutline',
  content: '<svg viewBox="0 0 48 48"><path d="M41.1 22.5c.22 0 .4.18.4.4v2.2a.4.4 0 01-.4.4H6.9a.4.4 0 01-.4-.4v-2.2c0-.22.18-.4.4-.4h34.2z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
