// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-MoreOutline',
  name: 'MoreOutline',
  content: '<svg viewBox="0 0 48 48"><path d="M12 21a3 3 0 110 6 3 3 0 010-6zm12 0a3 3 0 110 6 3 3 0 010-6zm12 0a3 3 0 110 6 3 3 0 010-6z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
