// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-MovieOutline',
  name: 'MovieOutline',
  content: '<svg viewBox="0 0 48 48"><path d="M23 3c11.598 0 21 9.402 21 21 0 5.724-2.29 10.913-6.004 14.7h-4.868c4.665-3.22 7.722-8.603 7.722-14.7 0-9.858-7.992-17.85-17.85-17.85S5.15 14.142 5.15 24 13.142 41.85 23 41.85h21V45H23C11.402 45 2 35.598 2 24S11.402 3 23 3zm0 26a5 5 0 110 10 5 5 0 010-10zm0 3a2 2 0 100 4 2 2 0 000-4zM13 19a5 5 0 110 10 5 5 0 010-10zm20 0a5 5 0 110 10 5 5 0 010-10zm-20 3a2 2 0 100 4 2 2 0 000-4zm20 0a2 2 0 100 4 2 2 0 000-4zM23 9a5 5 0 110 10 5 5 0 010-10zm0 3a2 2 0 100 4 2 2 0 000-4z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
