// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-PictureOutline',
  name: 'PictureOutline',
  content: '<svg viewBox="0 0 48 48"><g fill-rule="nonzero"><path d="M38 4a6 6 0 016 6v28a6 6 0 01-6 6H10a6 6 0 01-6-6V10a6 6 0 016-6h28zm0 3H10a3 3 0 00-2.995 2.824L7 10v28a3 3 0 002.824 2.995L10 41h28a3 3 0 002.995-2.824L41 38v-.668l-8.22-8.22a1.875 1.875 0 00-2.548-.095l-.103.096-12.887 12.886H13l15.627-15.626a4 4 0 015.656 0l6.034 6.033a.4.4 0 00.683-.283V10a3 3 0 00-2.824-2.995L38 7z"/><path d="M16 12a5 5 0 110 10 5 5 0 010-10zm0 3a2 2 0 100 4 2 2 0 000-4z"/></g></svg>',
}

export default getIconByMeta(meta)
