// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-PlayOutline',
  name: 'PlayOutline',
  content: '<svg viewBox="0 0 48 48"><path d="M13.754 5c.68 0 1.348.179 1.932.517l26.49 15.37c1.779 1.031 2.355 3.261 1.288 4.98-.317.511-.759.939-1.287 1.246l-26.491 15.37c-1.778 1.03-4.084.473-5.151-1.246A3.54 3.54 0 0110 39.369V8.63C10 6.625 11.68 5 13.754 5zm0 2.723a.928.928 0 00-.932.801l-.006.106v30.74c0 .5.42.907.938.907a.967.967 0 00.386-.08l.097-.05 26.491-15.37a.89.89 0 00.09-1.496l-.09-.06-26.491-15.37a.964.964 0 00-.483-.128z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
