// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-QuestionCircleFill',
  name: 'QuestionCircleFill',
  content: '<svg viewBox="0 0 48 48"><path d="M24 2c12.15 0 22 9.85 22 22s-9.85 22-22 22S2 36.15 2 24 11.85 2 24 2zm1.6 30h-2.2a.4.4 0 00-.4.4v2.2c0 .22.18.4.4.4h2.2a.4.4 0 00.4-.4v-2.2a.4.4 0 00-.4-.4zM24 12a7 7 0 00-7 7h3a4 4 0 114 4h-.6a.4.4 0 00-.4.4v5.2c0 .22.18.4.4.4h2.2a.4.4 0 00.4-.4l.001-2.89A7 7 0 0024 12z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
