// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-ReceiptOutline',
  name: 'ReceiptOutline',
  content: '<svg viewBox="0 0 48 48"><path d="M36 4a6 6 0 016 6v25.714L45 35v3l-21 5-21-5v-3l3 .714V10a6 6 0 016-6h24zm0 3H12a3 3 0 00-2.995 2.824L9 10v26.429L24 40l15-3.571V10a3 3 0 00-2.824-2.995L36 7zm-6.518 4.654l.073.033 1.896 1.09.001.001.066.047a.4.4 0 01.113.426l-.033.074-5.043 8.712 4.545.001c.22 0 .4.18.4.4v2.193a.4.4 0 01-.4.4h-5.6v1.994h5.6c.22 0 .4.18.4.4v2.193a.4.4 0 01-.4.4h-5.6V34.6a.4.4 0 01-.4.4h-2.2a.4.4 0 01-.4-.4v-4.583h-5.6a.4.4 0 01-.4-.4v-2.192c0-.22.18-.4.4-.4h5.6V25.03h-5.6a.4.4 0 01-.4-.4v-2.192c0-.22.18-.4.4-.4h4.429l-5.043-8.713a.4.4 0 01.146-.547l1.897-1.091a.4.4 0 01.546.146l5.067 8.755 5.068-8.755a.4.4 0 01.472-.18z" fill-rule="evenodd"/></svg>',
}

export default getIconByMeta(meta)
