// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-RightOutline',
  name: 'RightOutline',
  content: '<svg viewBox="0 0 48 48"><path d="M17.395 5.112l18.182 17.55c.553.55.586 1.424.097 2.014l-.097.107-18.181 18.1a.4.4 0 01-.283.117h-3.126a.4.4 0 01-.283-.683L32.32 23.782 13.724 5.687A.4.4 0 0114.003 5h3.114a.4.4 0 01.278.112z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
