// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-ShrinkOutline',
  name: 'ShrinkOutline',
  content: '<svg viewBox="0 0 48 48"><path d="M36.878 25.18L39 27.359a.4.4 0 01-.286.679h-9.261l11.275 11.576a.4.4 0 010 .558l-1.493 1.534a.4.4 0 01-.573 0L27.487 30.232v8.822a.4.4 0 01-.686.28l-2.102-2.159a.4.4 0 01-.113-.279V28.04c0-1.646 1.296-2.98 2.894-2.98h9.112a.4.4 0 01.286.121zM9.338 6.294l11.34 11.643V9.529a.4.4 0 01.687-.279l2.13 2.188a.4.4 0 01.114.279v8.327c0 1.662-1.308 3.01-2.923 3.01l-9.57-.001a.4.4 0 01-.287-.12l-2.15-2.21a.4.4 0 01.286-.679h9.662L7.272 8.386a.4.4 0 010-.558l1.493-1.534a.4.4 0 01.573 0z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
