// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-StopOutline',
  name: 'StopOutline',
  content: '<svg viewBox="0 0 48 48"><path d="M24 2c12.15 0 22 9.85 22 22s-9.85 22-22 22S2 36.15 2 24 11.85 2 24 2zM5 24c0 10.493 8.507 19 19 19a18.918 18.918 0 0012.333-4.546l-.652-.652-25.27-25.27-.865-.865a27.81 27.81 0 00-.78.975A18.916 18.916 0 005 24zM24 5a18.916 18.916 0 00-12.332 4.545l.848.849L37.82 35.698l.635.635A18.918 18.918 0 0043 24c0-10.493-8.507-19-19-19z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
