// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-TextOutline',
  name: 'TextOutline',
  content: '<svg viewBox="0 0 48 48"><path d="M31.343 3a4 4 0 012.829 1.172l7.656 7.656A4 4 0 0143 14.657V39a6 6 0 01-6 6H11a6 6 0 01-6-6V9a6 6 0 016-6h20.343zM30 6H11a3 3 0 00-2.995 2.824L8 9v30a3 3 0 002.824 2.995L11 42h26a3 3 0 002.995-2.824L40 39V17h-7a3 3 0 01-3-3V6zm7 19.4v2.2a.4.4 0 01-.4.4H11.4a.4.4 0 01-.4-.4v-2.2c0-.22.18-.4.4-.4h25.2c.22 0 .4.18.4.4zm-13-6v2.2a.4.4 0 01-.4.4H11.4a.4.4 0 01-.4-.4v-2.2c0-.22.18-.4.4-.4h12.2c.22 0 .4.18.4.4zm9-11.192v5.389a.4.4 0 00.403.4l5.349-.04a.4.4 0 00.28-.683l-5.35-5.35a.4.4 0 00-.682.284z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
