// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-TravelOutline',
  name: 'TravelOutline',
  content: '<svg viewBox="0 0 48 48"><path d="M44 31v7a6 6 0 01-6 6h-7v-3h7a3 3 0 002.995-2.824L41 38v-7h3zM7 31v7a3 3 0 002.824 2.995L10 41h7v3h-7a6 6 0 01-6-6v-7h3zm28.012-17.505a1 1 0 01-.007.785l-9.311 21.344a.628.628 0 01-1.172-.055l-1.684-5.298a4 4 0 01.546-3.522l4.373-6.182-6.808 3.978a4 4 0 01-3.364.312l-5.174-1.849a.626.626 0 01-.026-1.165l21.319-8.886a1 1 0 011.308.538zM38 4a6 6 0 016 6v7h-3v-7a3 3 0 00-2.824-2.995L38 7h-7V4h7zM17 4v3h-7a3 3 0 00-2.995 2.824L7 10v7H4v-7a6 6 0 016-6h7z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
