// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta'

const meta = {
  type: 'amd-UpOutline',
  name: 'UpOutline',
  content: '<svg viewBox="0 0 48 48"><path d="M5.112 30.705l17.55-18.182a1.495 1.495 0 012.014-.097l.107.097 18.1 18.182a.4.4 0 01.117.282v3.127a.4.4 0 01-.683.282L23.782 15.78 5.687 34.376A.4.4 0 015 34.098v-3.115a.4.4 0 01.112-.278z" fill-rule="nonzero"/></svg>',
}

export default getIconByMeta(meta)
