// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-AddCircleOutline',
  name: 'AddCircleOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M24 2c12.15 0 22 9.85 22 22s-9.85 22-22 22S2 36.15 2 24 11.85 2 24 2zm0 3C13.507 5 5 13.507 5 24s8.507 19 19 19 19-8.507 19-19S34.493 5 24 5zm1.5 9.9v7.6h7.6c.22 0 .4.18.4.4v2.2a.4.4 0 01-.4.4h-7.6v7.6a.4.4 0 01-.4.4h-2.2a.4.4 0 01-.4-.4v-7.6h-7.6a.4.4 0 01-.4-.4v-2.2c0-.22.18-.4.4-.4h7.6v-7.6c0-.22.18-.4.4-.4h2.2c.22 0 .4.18.4.4z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
