// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-AppstoreOutline',
  name: 'AppstoreOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M17 25a6 6 0 016 6v7a6 6 0 01-6 6h-7a6 6 0 01-6-6v-7a6 6 0 016-6h7zm21 0a6 6 0 016 6v7a6 6 0 01-6 6h-7a6 6 0 01-6-6v-7a6 6 0 016-6h7zm-21 3h-7a3 3 0 00-2.995 2.824L7 31v7a3 3 0 002.824 2.995L10 41h7a3 3 0 002.995-2.824L20 38v-7a3 3 0 00-2.824-2.995L17 28zm21 0h-7a3 3 0 00-2.995 2.824L28 31v7a3 3 0 002.824 2.995L31 41h7a3 3 0 002.995-2.824L41 38v-7a3 3 0 00-2.824-2.995L38 28zM17 4a6 6 0 016 6v7a6 6 0 01-6 6h-7a6 6 0 01-6-6v-7a6 6 0 016-6h7zm21 0a6 6 0 016 6v7a6 6 0 01-6 6h-7a6 6 0 01-6-6v-7a6 6 0 016-6h7zM17 7h-7a3 3 0 00-2.995 2.824L7 10v7a3 3 0 002.824 2.995L10 20h7a3 3 0 002.995-2.824L20 17v-7a3 3 0 00-2.824-2.995L17 7zm21 0h-7a3 3 0 00-2.995 2.824L28 10v7a3 3 0 002.824 2.995L31 20h7a3 3 0 002.995-2.824L41 17v-7a3 3 0 00-2.824-2.995L38 7z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
