// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-ArrowsAltOutline',
  name: 'ArrowsAltOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M27.54 25.42L38 35.878V26.5a.4.4 0 01.683-.283l2.2 2.2A.4.4 0 0141 28.7V38a3 3 0 01-2.824 2.994L38 41h-9.298a.4.4 0 01-.283-.117l-2.2-2.2a.4.4 0 01.283-.683h9.376L25.42 27.54a.4.4 0 010-.565l1.556-1.556a.4.4 0 01.565 0zM19.58 7.116l2.2 2.2a.4.4 0 01-.283.683h-9.376l10.46 10.46a.4.4 0 010 .566l-1.555 1.556a.4.4 0 01-.566 0L10 12.122v9.376a.4.4 0 01-.683.283l-2.2-2.2A.4.4 0 017 19.298v-9.297a3 3 0 012.824-2.995L10 7.001 19.297 7a.4.4 0 01.283.117z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
