// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-BankcardOutline',
  name: 'BankcardOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M39 5a6 6 0 016 6v26a6 6 0 01-6 6H9a6 6 0 01-6-6V11a6 6 0 016-6h30zm0 3H9a3 3 0 00-2.995 2.824L6 11v26a3 3 0 002.824 2.995L9 40h30a3 3 0 002.995-2.824L42 37V11a3 3 0 00-2.824-2.995L39 8zm4 7.4v2.2a.4.4 0 01-.4.4H5.4a.4.4 0 01-.4-.4v-2.2c0-.22.18-.4.4-.4h37.2c.22 0 .4.18.4.4zm-24 18v2.2a.4.4 0 01-.4.4h-8.2a.4.4 0 01-.4-.4v-2.2c0-.22.18-.4.4-.4h8.2c.22 0 .4.18.4.4z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
