// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-BellOutline',
  name: 'BellOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M7 38v-.035A3.5 3.5 0 014 34.5v-1.843a4 4 0 011.172-2.829L7 28v-7c0-9.389 7.611-17 17-17s17 7.611 17 17v7l1.828 1.828A4 4 0 0144 32.657V34.5a3.5 3.5 0 01-3 3.464V38H30.93a7.002 7.002 0 01-13.86 0H7zm20.874 0h-7.749l.055.19a4.002 4.002 0 007.64 0l.054-.19zM24 7c-7.628 0-13.83 6.1-13.997 13.687L10 21v8.077a.4.4 0 01-.117.283l-2.59 2.59a1 1 0 00-.284.575L7 32.657V34.5c0 .218.142.407.338.474l.087.02.041.006h33.067l.042-.005a.5.5 0 00.417-.404L41 34.5v-1.843a1 1 0 00-.206-.608l-.087-.1-2.59-2.59a.4.4 0 01-.117-.282V21c0-7.732-6.268-14-14-14z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
