// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-CalendarOutline',
  name: 'CalendarOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M18 4.4V7h12V4.4c0-.22.18-.4.4-.4h2.2c.22 0 .4.18.4.4V7h4a6 6 0 016 6v25a6 6 0 01-6 6H11a6 6 0 01-6-6V13a6 6 0 016-6h4V4.4c0-.22.18-.4.4-.4h2.2c.22 0 .4.18.4.4zM40 20H8v18a3 3 0 002.824 2.995L11 41h26a3 3 0 002.995-2.824L40 38V20zM15 10h-4a3 3 0 00-2.995 2.824L8 13v4h32v-4a3 3 0 00-2.824-2.995L37 10h-4v2.6a.4.4 0 01-.4.4h-2.2a.4.4 0 01-.4-.4V10H18v2.6a.4.4 0 01-.4.4h-2.2a.4.4 0 01-.4-.4V10z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
