// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-CheckOutline',
  name: 'CheckOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M44.31 12.684L21.218 35.566a1.504 1.504 0 01-2.252-.157 1.468 1.468 0 01-.158-.136L3.69 20.292a.4.4 0 01.282-.684h3.09a.4.4 0 01.282.116l12.816 12.7 20.496-20.308a.4.4 0 01.282-.116h3.09a.4.4 0 01.282.684z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
