// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-CheckCircleOutline',
  name: 'CheckCircleOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M24 2c12.15 0 22 9.85 22 22s-9.85 22-22 22S2 36.15 2 24 11.85 2 24 2zm0 3C13.507 5 5 13.507 5 24s8.507 19 19 19 19-8.507 19-19S34.493 5 24 5zm11.94 12.682L23.343 30.278a1.5 1.5 0 01-2.121 0l-.077-.082a1.502 1.502 0 01-.306-.236l-7.278-7.278a.4.4 0 01.283-.683h3.111a.4.4 0 01.283.117l5.012 5.012 10.012-10.012a.4.4 0 01.283-.117h3.112a.4.4 0 01.283.683z" fill-rule="evenodd"/></svg>',
};

export default getIconByMeta(meta);
