// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-ClockCircleFill',
  name: 'ClockCircleFill',
  content:
    '<svg viewBox="0 0 48 48"><path d="M24 2c12.15 0 22 9.85 22 22s-9.85 22-22 22S2 36.15 2 24 11.85 2 24 2zm.6 12h-2.2a.4.4 0 00-.4.4v8.772l.007.213a3.5 3.5 0 001.018 2.261l8.131 8.132a.4.4 0 00.566 0l1.556-1.556a.4.4 0 000-.566l-8.132-8.13-.05-.06a.5.5 0 01-.096-.294V14.4a.4.4 0 00-.4-.4z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
