// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-ClockCircleOutline',
  name: 'ClockCircleOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M24 2c12.15 0 22 9.85 22 22s-9.85 22-22 22S2 36.15 2 24 11.85 2 24 2zm0 3C13.507 5 5 13.507 5 24s8.507 19 19 19 19-8.507 19-19S34.493 5 24 5zm.6 9c.22 0 .4.18.4.4v8.772a.5.5 0 00.095.293l.051.06 8.132 8.131a.4.4 0 010 .566l-1.556 1.556a.4.4 0 01-.566 0l-8.13-8.132a3.5 3.5 0 01-1.02-2.261L22 23.172V14.4c0-.22.18-.4.4-.4h2.2z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
