// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-CloseOutline',
  name: 'CloseOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M10.609 8.118L24.177 21.82 37.744 8.118a.4.4 0 01.285-.119h3.075a.4.4 0 01.284.681l-15.11 15.26 15.224 15.378a.4.4 0 01-.284.681h-3.075a.4.4 0 01-.284-.119L24.177 26.062 10.494 39.88a.4.4 0 01-.285.119H7.136a.4.4 0 01-.284-.681L22.076 23.94 6.966 8.68a.4.4 0 01.284-.682h3.074a.4.4 0 01.285.119z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
