// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-CloseCircleOutline',
  name: 'CloseCircleOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M24 2c12.15 0 22 9.85 22 22s-9.85 22-22 22S2 36.15 2 24 11.85 2 24 2zm0 3C13.507 5 5 13.507 5 24s8.507 19 19 19 19-8.507 19-19S34.493 5 24 5zm-5.625 11.117L24 21.742l5.625-5.625a.4.4 0 01.283-.117h3.112a.4.4 0 01.283.683l-7.182 7.18 7.454 7.454a.4.4 0 01-.283.683H30.18a.4.4 0 01-.283-.117L24 25.985 18.1 31.883a.4.4 0 01-.283.117h-3.11a.4.4 0 01-.283-.683l7.453-7.453-7.181-7.181A.4.4 0 0114.98 16h3.112a.4.4 0 01.283.117z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
