// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-CollectMoneyOutline',
  name: 'CollectMoneyOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M38 4a6 6 0 016 6v28a6 6 0 01-6 6H10a6 6 0 01-6-6V10a6 6 0 016-6h28zm0 3H10a3 3 0 00-2.995 2.824L7 10v28a3 3 0 002.824 2.995L10 41h28a3 3 0 002.995-2.824L41 38V10a3 3 0 00-2.824-2.995L38 7zM14.6 18c.22 0 .4.18.4.4v12.2a.4.4 0 01-.4.4h-2.2a.4.4 0 01-.4-.4V18.4c0-.22.18-.4.4-.4h2.2zm7 0c.22 0 .4.18.4.4v12.2a.4.4 0 01-.4.4h-2.2a.4.4 0 01-.4-.4V18.4c0-.22.18-.4.4-.4h2.2zm7 0c.22 0 .4.18.4.4v12.2a.4.4 0 01-.4.4h-2.2a.4.4 0 01-.4-.4V18.4c0-.22.18-.4.4-.4h2.2zm7 0c.22 0 .4.18.4.4v12.2a.4.4 0 01-.4.4h-2.2a.4.4 0 01-.4-.4V18.4c0-.22.18-.4.4-.4h2.2z" fill-rule="evenodd"/></svg>',
};

export default getIconByMeta(meta);
