// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-DownCircleOutline',
  name: 'DownCircleOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M24 2c12.15 0 22 9.85 22 22s-9.85 22-22 22S2 36.15 2 24 11.85 2 24 2zm0 3C13.507 5 5 13.507 5 24s8.507 19 19 19 19-8.507 19-19S34.493 5 24 5zm-7.33 13.537l7.944 7.26 7.716-7.052a.4.4 0 01.67.295v2.976a.4.4 0 01-.13.296l-7.19 6.57-.132.107a1.494 1.494 0 01-.754.28l-.16.005h-.02a1.496 1.496 0 01-.95-.295l-.116-.097-7.418-6.778a.4.4 0 01-.13-.296v-2.976a.4.4 0 01.67-.295z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
