// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-ExclamationCircleOutline',
  name: 'ExclamationCircleOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M24 2c12.15 0 22 9.85 22 22s-9.85 22-22 22S2 36.15 2 24 11.85 2 24 2zm0 3C13.507 5 5 13.507 5 24s8.507 19 19 19 19-8.507 19-19S34.493 5 24 5zm1.1 26c.22 0 .4.18.4.4v2.2a.4.4 0 01-.4.4h-2.2a.4.4 0 01-.4-.4v-2.2c0-.22.18-.4.4-.4h2.2zm0-17c.22 0 .4.18.4.4v13.2a.4.4 0 01-.4.4h-2.2a.4.4 0 01-.4-.4V14.4c0-.22.18-.4.4-.4h2.2z" fill-rule="evenodd"/></svg>',
};

export default getIconByMeta(meta);
