// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-ExclamationOutline',
  name: 'ExclamationOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M24.5 34a2.5 2.5 0 110 5 2.5 2.5 0 010-5zm1.1-26c.22 0 .4.18.4.4v22.2a.4.4 0 01-.4.4h-2.2a.4.4 0 01-.4-.4V8.4c0-.22.18-.4.4-.4h2.2z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
