// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-ExclamationTriangleOutline',
  name: 'ExclamationTriangleOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M25.423 5.013a3.896 3.896 0 011.453 1.46L43.99 36.66a3.916 3.916 0 01-1.453 5.327 3.87 3.87 0 01-1.923.512H6.386C4.24 42.5 2.5 40.752 2.5 38.595c0-.678.176-1.345.51-1.934L20.123 6.473a3.875 3.875 0 015.3-1.46zm-2.705 2.883l-.061.095-17.1 30.056a.973.973 0 00.73 1.446l.114.007h34.198a.97.97 0 00.894-1.352l-.05-.101-17.1-30.056a.971.971 0 00-1.625-.095zM24.965 32.9v2.2a.4.4 0 01-.4.4h-2.13a.4.4 0 01-.4-.4v-2.2c0-.22.179-.4.4-.4h2.13c.221 0 .4.18.4.4zm0-14v10.2a.4.4 0 01-.4.4h-2.13a.4.4 0 01-.4-.4V18.9c0-.22.179-.4.4-.4h2.13c.221 0 .4.18.4.4z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
