// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-FillinOutline',
  name: 'FillinOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M25 4.4v2.2a.4.4 0 01-.4.4H10a3 3 0 00-2.995 2.824L7 10v28a3 3 0 002.824 2.995L10 41h28a3 3 0 002.995-2.824L41 38V23.4c0-.22.18-.4.4-.4h2.2c.22 0 .4.18.4.4V38a6 6 0 01-6 6H10a6 6 0 01-6-6V10a6 6 0 016-6h14.6c.22 0 .4.18.4.4zm16.96 1.14a5 5 0 010 7.07L28.612 25.96a.4.4 0 01-.31.115l-6.086-.42a.4.4 0 01-.372-.37l-.42-6.087a.4.4 0 01.117-.31L34.889 5.54a5 5 0 017.071 0zm-8.185 5.356l-9.147 9.147a.4.4 0 00-.116.31l.17 2.465 2.465.17a.4.4 0 00.31-.117l9.146-9.147-2.828-2.828zM37.12 7.56l-.11.102-1.114 1.113 2.83 2.83 1.113-1.114a2 2 0 00.102-2.72l-.102-.109a2 2 0 00-2.72-.102z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
