// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-FlagOutline',
  name: 'FlagOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M7.4 4h31.625C40.115 4 41 4.895 41 6c0 .164-.02.328-.06.488l-3.082 12.416a.4.4 0 000 .192l3.082 12.416c.266 1.072-.376 2.158-1.434 2.428-.157.04-.319.06-.481.06H10.362a.4.4 0 00-.4.4v9.2a.4.4 0 01-.4.4H7.4a.4.4 0 01-.4-.4V4.4c0-.22.18-.4.4-.4zm29.847 3H10.362a.4.4 0 00-.4.4v23.2c0 .22.18.4.4.4h26.885a.4.4 0 00.388-.496l-2.832-11.408a.4.4 0 010-.192l2.832-11.408A.4.4 0 0037.247 7z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
