// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-FrownFill',
  name: 'FrownFill',
  content:
    '<svg viewBox="0 0 48 48"><path d="M24 2c12.15 0 22 9.85 22 22s-9.85 22-22 22S2 36.15 2 24 11.85 2 24 2zm0 24a19.91 19.91 0 00-9.796 2.56.4.4 0 00-.204.348v2.583a.4.4 0 00.625.331c.141-.096.239-.161.293-.195A16.92 16.92 0 0124 29c3.337 0 6.45.961 9.075 2.622.058.037.159.104.301.2a.4.4 0 00.625-.33v-2.584a.4.4 0 00-.203-.348A19.91 19.91 0 0024 26zm-8-8a2 2 0 100 4 2 2 0 000-4zm16 0a2 2 0 100 4 2 2 0 000-4z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
