// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-HeartFill',
  name: 'HeartFill',
  content:
    '<svg viewBox="0 0 48 48"><path d="M6.603 8.73c4.594-4.756 11.917-4.964 16.75-.624l.313.293.05.05a.4.4 0 00.566 0l.126-.122c4.827-4.567 12.319-4.432 16.989.404 4.804 4.974 4.804 13.04 0 18.014L26.899 41.756a4.002 4.002 0 01-5.798 0L6.603 26.745c-4.804-4.975-4.804-13.04 0-18.014z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
