// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-LeftOutline',
  name: 'LeftOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M31.705 5.112l-18.182 17.55a1.495 1.495 0 00-.097 2.014l.097.107 18.182 18.1a.4.4 0 00.282.117h3.127a.4.4 0 00.282-.683L16.78 23.782 35.376 5.687A.4.4 0 0035.098 5h-3.115a.4.4 0 00-.278.112z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
