// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-LocationFill',
  name: 'LocationFill',
  content:
    '<svg viewBox="0 0 48 48"><path d="M24 4c9.389 0 17 7.625 17 17.03 0 4.204-1.52 8.053-4.042 11.023l-.293.342c-1.944 2.233-5.516 5.84-10.717 10.82a2.81 2.81 0 01-3.757.126l-.14-.126-1.617-1.556c-4.585-4.429-7.716-7.63-9.39-9.604A16.981 16.981 0 017 21.03C7 11.625 14.611 4 24 4zm0 10.507c-3.651 0-6.611 2.994-6.611 6.685 0 3.694 2.96 6.687 6.611 6.687s6.611-2.994 6.611-6.686c0-3.692-2.96-6.686-6.611-6.686z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
