// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-LockOutline',
  name: 'LockOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M24 4c6.627 0 12 5.362 12 11.977v6.065h1c2.21 0 4 1.788 4 3.993v13.973A3.996 3.996 0 0137 44H11c-2.21 0-4-1.787-4-3.992V26.035a3.996 3.996 0 014-3.993h1v-6.065C12 9.362 17.373 4 24 4zm13 21.036H11a1 1 0 00-.993.882l-.007.117v13.973c0 .512.386.933.883.991l.117.007h26a1 1 0 00.993-.882l.007-.116V26.035a.999.999 0 00-.883-.992L37 25.036zM26 30.35v5.189a.4.4 0 01-.4.4h-2.2a.4.4 0 01-.4-.4V30.35c0-.22.18-.4.4-.4h2.2c.22 0 .4.18.4.4zM24 6.994c-4.882 0-8.856 3.88-8.996 8.718l-.004.265v5.988h18v-5.988c0-4.872-3.887-8.839-8.735-8.979L24 6.994z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
