// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-MailFill',
  name: 'MailFill',
  content:
    '<svg viewBox="0 0 48 48"><path d="M37 5c4.418 0 8 3.78 8 8.444v21.112C45 39.219 41.418 43 37 43H11c-4.418 0-8-3.78-8-8.444V13.444C3 8.781 6.582 5 11 5h26zm4.961 9.043a.391.391 0 00-.533-.2l-15.278 7.68-.243.114a4.76 4.76 0 01-4.057-.113l-15.278-7.68a.391.391 0 00-.533.2.444.444 0 00-.039.182v2.57c0 .164.088.313.228.383l14.333 7.203a7.621 7.621 0 006.878 0l14.333-7.203a.425.425 0 00.228-.382v-2.571a.441.441 0 00-.039-.182v-.001z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
