// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-PayOutline',
  name: 'PayOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M31.809 9.33a.4.4 0 01.54-.146l1.894 1.067a.4.4 0 01.148.552L28.08 21.509h6.52c.22 0 .4.18.4.4v2.144a.4.4 0 01-.4.4l-8.6-.001v3.04h8.6c.22 0 .4.18.4.4v2.144a.4.4 0 01-.4.4l-8.6-.001v10.299a.4.4 0 01-.4.4h-2.2a.4.4 0 01-.4-.4V30.435h-8.6a.4.4 0 01-.4-.4v-2.143c0-.22.18-.4.4-.4H23v-3.04h-8.6a.4.4 0 01-.4-.4V21.91c0-.22.18-.4.4-.4h7.118l-6.31-10.706a.4.4 0 01.147-.552l1.893-1.067a.4.4 0 01.541.145l7.009 11.891z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
