// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-PicturesOutline',
  name: 'PicturesOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M32 10a6 6 0 016 6v22a6 6 0 01-6 6H10a6 6 0 01-6-6V16a6 6 0 016-6h22zm0 3H10a3 3 0 00-2.995 2.824L7 16v22a3 3 0 002.824 2.995L10 41h22a3 3 0 002.995-2.824L35 38v-4.668l-4.22-4.22a1.875 1.875 0 00-2.548-.095l-.103.096-11.32 11.319-.567.567H12l14.627-14.626a4 4 0 015.656 0L35 29.089V16a3 3 0 00-2.824-2.995L32 13zm6-9a6 6 0 016 6v24h-3V10a3 3 0 00-2.824-2.995L38 7H14V4h24zM14.5 16a4.5 4.5 0 110 9 4.5 4.5 0 010-9zm0 3a1.5 1.5 0 100 3 1.5 1.5 0 000-3z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
