// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-PieOutline',
  name: 'PieOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M24 2c12.15 0 22 9.85 22 22s-9.85 22-22 22S2 36.15 2 24 11.85 2 24 2zM5 24c0 10.493 8.507 19 19 19 4.701 0 9.004-1.707 12.32-4.536L23.686 26.261a5.5 5.5 0 01-1.679-3.7L22 22.3V5.104C12.448 6.104 5 14.182 5 24zm37.974 1H26.698l11.746 11.344A18.918 18.918 0 0042.974 25zM25 5.026V22h17.896C41.931 12.774 34.362 5.512 25 5.027z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
