// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-SearchOutline',
  name: 'SearchOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M10.243 10.15c6.992-6.867 18.327-6.867 25.318 0a17.36 17.36 0 01.684 24.16l7.465 7.332a.4.4 0 010 .57l-1.54 1.513a.4.4 0 01-.56 0l-7.532-7.4c-7.03 5.53-17.319 5.095-23.835-1.305a17.366 17.366 0 010-24.87zm2.11 2.073a14.471 14.471 0 000 20.724c5.826 5.723 15.272 5.723 21.098 0a14.471 14.471 0 000-20.724c-5.826-5.723-15.272-5.723-21.098 0z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
