// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-SendOutline',
  name: 'SendOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M25 4.4v2.199a.4.4 0 01-.401.4L10 7a3 3 0 00-2.995 2.824L7 10v28a3 3 0 002.824 2.995L10 41h28a3 3 0 002.995-2.824L41 38l-.001-14.6a.4.4 0 01.4-.4H43.6a.4.4 0 00.4-.4v-5.2a.4.4 0 00-.4-.4h-2.2a.4.4 0 01-.4-.4V8.914L26.564 23.349a.4.4 0 01-.565 0l-1.556-1.556a.4.4 0 010-.565L38.67 7H31.4a.4.4 0 01-.4-.4V4.4c0-.22.18-.4.4-.4h11.1A1.5 1.5 0 0144 5.5V38a6 6 0 01-6 6H10a6 6 0 01-6-6V10a6 6 0 016-6h14.6a.4.4 0 01.4.4z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
