// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-ShopbagOutline',
  name: 'ShopbagOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M37 4a6 6 0 016 6v28a6 6 0 01-6 6H11a6 6 0 01-6-6V10a6 6 0 016-6h26zm3 32H8v2a3 3 0 002.824 2.995L11 41h26a3 3 0 002.995-2.824L40 38v-2zM37 7H11a3 3 0 00-2.995 2.824L8 10v23h32V10a3 3 0 00-2.824-2.995L37 7zm-17.617 5c.202 0 .367.165.367.367v2.383a4.583 4.583 0 004.384 4.579l.2.004a4.583 4.583 0 004.578-4.384l.005-.199v-2.383c0-.202.165-.367.366-.367H31.3c.202 0 .367.165.367.367v2.383a7.333 7.333 0 01-14.667 0v-2.383c0-.202.165-.367.367-.367h2.016z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
