// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-SmileFill',
  name: 'SmileFill',
  content:
    '<svg viewBox="0 0 48 48"><path d="M24 2c12.15 0 22 9.85 22 22s-9.85 22-22 22S2 36.15 2 24 11.85 2 24 2zm-9.586 24.45a.265.265 0 00-.41.165l-.005.053V29.5l.01.085a.4.4 0 00.194.263l.258.144A19.91 19.91 0 0024 32.409a19.912 19.912 0 009.797-2.56.4.4 0 00.204-.35v-2.727l-.008-.073a.32.32 0 00-.435-.222l-.056.03-.342.225A16.92 16.92 0 0124 29.41a16.921 16.921 0 01-9.586-2.96zM16 18a2 2 0 100 4 2 2 0 000-4zm16 0a2 2 0 100 4 2 2 0 000-4z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
