// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-SmileOutline',
  name: 'SmileOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M24 2c12.15 0 22 9.85 22 22s-9.85 22-22 22S2 36.15 2 24 11.85 2 24 2zm0 3C13.507 5 5 13.507 5 24s8.507 19 19 19 19-8.507 19-19S34.493 5 24 5zm-9.954 21.517a.265.265 0 01.368-.067l.082.056A16.921 16.921 0 0024 29.409c3.52 0 6.79-1.07 9.502-2.902l.056-.03a.32.32 0 01.443.295V29.5a.4.4 0 01-.204.348A19.912 19.912 0 0124 32.408a19.91 19.91 0 01-9.797-2.56.4.4 0 01-.204-.348v-2.832l.005-.053a.265.265 0 01.042-.098zM16 18a2 2 0 110 4 2 2 0 010-4zm16 0a2 2 0 110 4 2 2 0 010-4z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
