// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-StarFill',
  name: 'StarFill',
  content:
    '<svg viewBox="0 0 48 48"><path d="M25.846 4.449a4.259 4.259 0 011.894 1.97l3.92 8.265 8.768 1.325c2.28.345 3.86 2.547 3.528 4.918a4.402 4.402 0 01-1.216 2.483l-6.344 6.433 1.497 9.084c.39 2.362-1.135 4.605-3.405 5.01a4.03 4.03 0 01-2.646-.436L24 39.212l-7.842 4.289c-2.04 1.115-4.56.3-5.633-1.822a4.492 4.492 0 01-.419-2.752l1.498-9.084L5.26 23.41c-1.65-1.673-1.684-4.42-.076-6.135a4.117 4.117 0 012.387-1.266l8.768-1.325 3.92-8.264c1.02-2.15 3.521-3.031 5.587-1.971z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
