// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-TagOutline',
  name: 'TagOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M43 39.98c0 2.22-1.79 4.019-4 4.019-.463 0-.923-.08-1.359-.24l-13.514-4.544a.4.4 0 00-.254 0L10.359 43.76a3.995 3.995 0 01-5.121-2.416A4.037 4.037 0 015 39.98V9.03C5 5.7 7.686 3 11 3h26c3.314 0 6 2.7 6 6.03v30.95zm-3-24.921H8v24.92a1 1 0 001.228.979l.112-.034 14.532-4.914a.4.4 0 01.256 0l14.532 4.914a.996.996 0 001.333-.828L40 39.98V15.06zm-3-9.044H11a3.007 3.007 0 00-2.995 2.837L8 9.03v3.014h32V9.03a3.009 3.009 0 00-2.824-3.01L37 6.015z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
