// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-UnlockOutline',
  name: 'UnlockOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M24 4c6.627 0 12 5.373 12 12v6h1a4 4 0 014 4v14a4 4 0 01-4 4H11a4 4 0 01-4-4V26a4 4 0 014-4h22v-6a9 9 0 00-8.735-8.996L24 7a9 9 0 00-8.996 8.735L15 16v2.6a.4.4 0 01-.4.4h-2.2a.4.4 0 01-.4-.4V16c0-6.627 5.373-12 12-12zm13 21H11a1 1 0 00-.993.883L10 26v14a1 1 0 00.883.993L11 41h26a1 1 0 00.993-.883L38 40V26a1 1 0 00-.883-.993L37 25zm-11 5.4v5.2a.4.4 0 01-.4.4h-2.2a.4.4 0 01-.4-.4v-5.2c0-.22.18-.4.4-.4h2.2c.22 0 .4.18.4.4z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
