// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-UnorderedListOutline',
  name: 'UnorderedListOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M8.5 32a4.5 4.5 0 110 9 4.5 4.5 0 010-9zm0 3a1.5 1.5 0 100 3 1.5 1.5 0 000-3zm35.1 0c.22 0 .4.18.4.4v2.2a.4.4 0 01-.4.4H16.4a.4.4 0 01-.4-.4v-2.2c0-.22.18-.4.4-.4h27.2zM8.5 19a4.5 4.5 0 110 9 4.5 4.5 0 010-9zm0 3a1.5 1.5 0 100 3 1.5 1.5 0 000-3zm35.1 0c.22 0 .4.18.4.4v2.2a.4.4 0 01-.4.4H16.4a.4.4 0 01-.4-.4v-2.2c0-.22.18-.4.4-.4h27.2zM8.5 6a4.5 4.5 0 110 9 4.5 4.5 0 010-9zm0 3a1.5 1.5 0 100 3 1.5 1.5 0 000-3zm35.1 0c.22 0 .4.18.4.4v2.2a.4.4 0 01-.4.4H16.4a.4.4 0 01-.4-.4V9.4c0-.22.18-.4.4-.4h27.2z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
