// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-UpCircleOutline',
  name: 'UpCircleOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M24 2c12.15 0 22 9.85 22 22s-9.85 22-22 22S2 36.15 2 24 11.85 2 24 2zm0 3C13.507 5 5 13.507 5 24s8.507 19 19 19 19-8.507 19-19S34.493 5 24 5zm.634 12.954c.32-.007.642.087.914.285l.132.107 7.19 6.57a.4.4 0 01.13.296v2.976a.4.4 0 01-.67.295l-7.716-7.052-7.944 7.26a.4.4 0 01-.67-.295V25.42a.4.4 0 01.13-.296l7.418-6.778c.264-.241.592-.37.924-.39l.162-.002z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
