// generated by scripts/icon.js
import getIconByMeta from '../getIconByMeta';

const meta = {
  type: 'amd-UploadOutline',
  name: 'UploadOutline',
  content:
    '<svg viewBox="0 0 48 48"><path d="M13.5 4.4v2.2a.4.4 0 01-.4.4H10a3 3 0 00-2.995 2.824L7 10v28a3 3 0 002.824 2.995L10 41h28a3 3 0 002.995-2.824L41 38V10a3 3 0 00-2.824-2.995L38 7h-2.1a.4.4 0 01-.4-.4V4.4c0-.22.18-.4.4-.4H38a6 6 0 016 6v28a6 6 0 01-6 6H10a6 6 0 01-6-6V10a6 6 0 016-6h3.1c.22 0 .4.18.4.4zM24.486 4c.345-.01.694.093.985.31l.122.1 8.277 7.565a.4.4 0 01.13.295v3.805a.053.053 0 01-.015.036.022.022 0 01-.03.001L26 8.844v21.64a.4.4 0 01-.4.4h-2.2a.4.4 0 01-.4-.4V8.816l-7.33 6.697a.4.4 0 01-.67-.295v-2.976a.4.4 0 01.13-.295l8.248-7.536A1.565 1.565 0 0124.486 4z" fill-rule="nonzero"/></svg>',
};

export default getIconByMeta(meta);
